@TestInitProject_Web_HostAddress = http://localhost:5164

GET {{TestInitProject_Web_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TestInitProject_Web_HostAddress}}/weatherforecast/connectionstring
Accept: application/json


###

POST {{TestInitProject_Web_HostAddress}}/Customer/
Accept: application/json
Content-Type: application/json

{
    "Name": "Lam duong 16",
    "Email": "test16@mailinator.com"
}

###
GET {{TestInitProject_Web_HostAddress}}/Customer?pageNumber=1&pageSize=10
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MWI5NTg0Ni02ZGJhLTRlY2MtYjVjOS01ZmJkZWFkNDhkNjYiLCJlbWFpbCI6InRlc3QxNkBtYWlsaW5hdG9yLmNvbSIsInBlcm1pc3Npb25zIjpbIlJlYWRDdXN0b21lciIsIkNyZWF0ZUN1c3RvbWVyIl0sImV4cCI6MTcxOTIyMjAyNSwiaXNzIjoiTGFtRHVvbmciLCJhdWQiOiJnYSJ9.h2Gfrq7w6MgnZsGUDXNzrmqb5qWkIMFzLArgEdJFWa8

###
POST {{TestInitProject_Web_HostAddress}}/Customer/Login
Accept: application/json
Content-Type: application/json

{
    "Email": "test16@mailinator.com"
}

